---
# ansible-satellite secrets
# YOU SHOULD ENCRYPT THIS FILE WITH ANSIBLE VAULT!
# EXAMPLE:
# ansible-vault encrypt secrets.yml

rhn_user: "admin"
rhn_pass: "Iaz6USksOy"
rhn_pool_id: ""
sat_admin_password: "Iaz6USksOy"

ansible_connection: ssh
ansible_user: redhat
ansible_ssh_pass: redhat
ansible_sudo_pass: redhat

# This is only needed if using a custom SSL certificate
#openssl_passphrase: "PASSWORD-TO-USE-FOR-OPENSSL-ENCRYPTION-OF-PRIVATE-KEY"
