---
# tasks file for satellite-clients

- name: Get current subscription repositories
  shell: 
    cmd: subscription-manager repos --list-enabled | grep -i 'Repo ID'
  register: enable_repos_id

- set_fact:
    enable_repos: "{{ enable_repos_id.stdout | regex_replace('Repo ID: ', '') }}"

- set_fact:
    enable_repos_list: "{{ enable_repos.split('\n') | lower }}"

